rc: .

diff --git a/bin/rc b/bin/rc
--- a/bin/rc
+++ b/bin/rc
@@ -17,7 +17,6 @@ cd "$(dirname "$0")/.."
 # TODO: Faltaría el SH y las variables de system.sh y probarlo un poco y los comandos de alias
 
 add() {
-  shift
   if test -d "${1:-.}"; then
     arguments="$(realpath -e "${1:-.}" | sed "s|${HOME}|~|")"
     alias="${arguments##*/}"
@@ -44,12 +43,14 @@ add() {
       >&2 echo "Already exists: ${prefix}${alias}=\"${value}\""
       exit 1
     else
-      echo "Alias ${alias} already exists with value: $(aliases | grep "^${prefix}${alias}=" | awk -F= '{ print $2 }')"
-      printf "%s" "Do you want to use a different alias name? [y/N] "
+      echo "Alias ${alias} already exists with value: ${existing}"
+      printf "%s" "Do you want to use a different alias name or delete? [y/N/D] "
       read -r yes
       if [ "${yes}" = "y" ]; then
         printf "%s" "New alias name: "
         read -r alias
+      elif [ "${yes}" = "D" ]; then
+        del "${prefix}${alias}"
       else
         return 0
       fi
@@ -68,9 +69,39 @@ add_var() { RC_VARS="${RC_VARS:+${RC_VARS} }$1"; }
 
 aliases() { env -i ENV="${_RC_FILE}" sh -li -c alias 2>/dev/null | sort -u; }
 
-alias_exists() { grep -R -l "alias ${1}=" "${RC_GENERATED_RC_D}"; }
+alias_exists() { grep -R -l "alias ${1}" "${RC_GENERATED_RC_D}"; }
 
-clean() { :; }
+clean() {
+  tmp="$(mktemp)"
+  id_like="${RC_GENERATED_RC_D}/${ID_LIKE}/dirs.sh"
+  set --
+  for supported in 00-common "${HOSTNAME}" "${ID_LIKE}" "${UNAME}"; do
+    file="${RC_GENERATED_RC_D}/${supported}/dirs.sh"
+    test -f "${file}" || continue
+    set -- "${file}" "$@"
+  done
+
+  find "$@" -type f -name dirs.sh -exec grep -E "alias .*=" "{}" \;
+#  echo "${HOSTNAME}"
+#  found="$(grep -ER "alias .*=" \
+#             "${RC_GENERATED_RC_D}/00-common/dirs.sh" \
+#             "${RC_GENERATED_RC_D}/${HOSTNAME}/dirs.sh" \
+#             "${RC_GENERATED_RC_D}/${ID_LIKE}/dirs.sh" \
+#             "${RC_GENERATED_RC_D}/${UNAME}/dirs.sh" \
+#               | while IFS=:= read -r file alias value; do
+#    [ "${line-}" ] || continue
+#    echo "${file}|${alias}|${value}"
+#    grep -v "${line}" "${file}" > "${tmp}" 2>/dev/null || true
+#    mv -v "${tmp}" "${file}"
+#  done)"
+#  if [ ! "${found-}" ]; then
+#    if aliases | grep -q "^${1}="; then
+#      add="; however alias that can not be deleted found in: $(grep -R -l "alias ${1}=" "${RC_ETC}")"
+#    fi
+#    >&2 echo "${1}: Alias not found in: ${RC_GENERATED_RC_D}${add-}"
+#    return 1
+#  fi
+}
 
 create_dirs_and_files() {
   for _gen_rc_dir in ${RC_SUPPORTED}; do
@@ -152,7 +183,22 @@ create_dirs_and_files() {
   done
 }
 
-del() { :; }
+del() {
+  tmp="$(mktemp)"
+  found="$(grep -R "alias ${1}" "${RC_GENERATED_RC_D}" | while IFS=: read -r file line; do
+    [ "${line-}" ] || continue
+    grep -v "${line}" "${file}" > "${tmp}" 2>/dev/null || true
+    mv -v "${tmp}" "${file}"
+  done)"
+  if [ ! "${found-}" ]; then
+    if aliases | grep -q "^${1}="; then
+      add="; however alias that can not be deleted found in: $(grep -R -l "alias ${1}=" "${RC_ETC}")"
+    fi
+    >&2 echo "${1}: Alias not found in: ${RC_GENERATED_RC_D}${add-}"
+    return 1
+  fi
+
+ }
 
 echo_rc_source_dir() { while read -r i; do echo "  ${1-}rc_source_dir \"${i}\""; done; }
 
@@ -242,12 +288,12 @@ generates \$ENV file and manages rc repository, with no options creates the stat
 Commands:
    -h, --help, help   display this help and exit.
    --force            force updating static \$ENV file ".${0}.sh" (valid with not commands, hook, install or supported)
-   add                to add a new alias to rc generated directory:
+   add                to add a new alias to rc generated directory "${RC_GENERATED_RC_D}":
                       - if argument is a directory ".basename" (default: cwd) will be
                         added to dirs.sh (default: "${HOSTNAME}" directory)
                       - it is added to sudo.sh if it is not a directory (default: "${UNAME}" directory).
    clean              to clean directory aliases which directory does not exist
-   del                deletes an alias
+   del                deletes an alias from rc generated directory "${RC_GENERATED_RC_D}"
    hook               shows the path to \$ENV file ".${0}.sh"
    list               show list of commands available and exit
    install            to install hooks into /etc/profile, ~/.profile, ~/.bashrc, ~/.bash_profile for user and root
@@ -436,16 +482,20 @@ supported() {
 main() {
   [ "${ENV-}" ] || set_vars
 
-  hook=false; supported=false
+  action=false; hook=false; supported=false
   for arg; do
     case "${arg}" in
       -h|--help|help) help 0;;
-      --force) RC_FORCE=1  ;;
-      add|aliases|clean|del|install|sync) function="${arg}" ;;
-      list) printf "%s\n" add clean del hook install "${arg}" supported sync ;;
-      supported) supported=true ;;
-      hook) hook=true ;;
-      *)
+      --force) RC_FORCE=1; shift  ;;
+      add|aliases|clean|del|install|sync)
+        if ! $action; then
+          function="${arg}"; action=true; shift
+        fi
+        ;;
+      list) printf "%s\n" add clean del hook install "${arg}" supported sync; exit ;;
+      supported) supported=true; shift ;;
+      hook) hook=true; shift ;;
+      -*)
         >&2 echo "${0##*/}: Unknown argument: ${arg}"
         >&2 echo
         >&2 help
